language: node_js
node_js:
  - 8

before_script:
  - echo $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 --decode --ignore-garbage > $GOOGLE_APPLICATION_CREDENTIALS

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | npx coveralls
